### ISSUE TITLE
在Spring Boot 2.1.9中无法使用

### ISSUE THREAD

**Issue by 619219223** [aLiang-xyl/integration-mqtt#3]
在Spring Boot 2.1.9中报以下错误，但是在2.2.5中正常，能不能出一个兼容2.1.9版本的呢？

[2020-08-21 09:25:36.707] [MQTT Call: maintenance_analysis_server_b2c0cc548f684e308dd108754c805fbf] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter : Unhandled exception for GenericMessage [payload=test111, headers={mqtt_receivedRetained=false, id=794fcb60-066f-420c-9794-2983e7db0a87, mqtt_duplicate=false, mqtt_receivedTopic=devices/system/test, mqtt_receivedQos=1, timestamp=1597973136705}]
org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'maintenance-analysis-server-1.testChannel'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=test111, headers={mqtt_receivedRetained=false, spanTraceId=1796e22f4f37dad7, spanId=1796e22f4f37dad7, nativeHeaders={spanTraceId=[1796e22f4f37dad7], spanId=[1796e22f4f37dad7], spanSampled=[1]}, mqtt_duplicate=false, X-B3-SpanId=1796e22f4f37dad7, X-B3-Sampled=1, X-B3-TraceId=1796e22f4f37dad7, id=1256ed97-8a4f-bd32-68cb-dd5f66488c4f, spanSampled=1, mqtt_receivedTopic=test1, mqtt_receivedQos=1, timestamp=1597973136706}]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:205)
	at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.messageArrived(MqttPahoMessageDrivenChannelAdapter.java:350)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:499)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:402)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:206)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:138)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	... 19 common frames omitted
[2020-08-21 09:25:36.710] [MQTT Call: maintenance_analysis_server_b2c0cc548f684e308dd108754c805fbf] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection: MqttException; retrying...

**Comment by aLiang-xyl** [comment]
您好，我将springboot切换到2.1.9版本，是可以正常使用的。经测试，您少了org.springframework.messaging.MessageHandler接口的实现，参见README.md中的

订阅消息


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aLiang-xyl/integration-mqtt"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月21日(星期五) 上午9:36
收件人:&nbsp;"aLiang-xyl/integration-mqtt"<integration-mqtt@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[aLiang-xyl/integration-mqtt] 在Spring Boot 2.1.9中无法使用 (#3)





 
在Spring Boot 2.1.9中报以下错误，但是在2.2.5中正常，能不能出一个兼容2.1.9版本的呢？
 
[2020-08-21 09:25:36.707] [MQTT Call: maintenance_analysis_server_b2c0cc548f684e308dd108754c805fbf] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter : Unhandled exception for GenericMessage [payload=test111, headers={mqtt_receivedRetained=false, id=794fcb60-066f-420c-9794-2983e7db0a87, mqtt_duplicate=false, mqtt_receivedTopic=devices/system/test, mqtt_receivedQos=1, timestamp=1597973136705}]
 org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'maintenance-analysis-server-1.testChannel'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=test111, headers={mqtt_receivedRetained=false, spanTraceId=1796e22f4f37dad7, spanId=1796e22f4f37dad7, nativeHeaders={spanTraceId=[1796e22f4f37dad7], spanId=[1796e22f4f37dad7], spanSampled=[1]}, mqtt_duplicate=false, X-B3-SpanId=1796e22f4f37dad7, X-B3-Sampled=1, X-B3-TraceId=1796e22f4f37dad7, id=1256ed97-8a4f-bd32-68cb-dd5f66488c4f, spanSampled=1, mqtt_receivedTopic=test1, mqtt_receivedQos=1, timestamp=1597973136706}]
 at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
 at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
 at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401)
 at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
 at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
 at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
 at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
 at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:205)
 at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.messageArrived(MqttPahoMessageDrivenChannelAdapter.java:350)
 at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:499)
 at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:402)
 at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:206)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
 at java.util.concurrent.FutureTask.run(FutureTask.java)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
 Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers
 at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:138)
 at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
 at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
 ... 19 common frames omitted
 [2020-08-21 09:25:36.710] [MQTT Call: maintenance_analysis_server_b2c0cc548f684e308dd108754c805fbf] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection: MqttException; retrying...

**Comment by aLiang-xyl** [comment]
由于bean加载顺序的原因导致消息订阅失败，您可以在启动类上添加@ComponentScan(basePackages = {"com.framework.mqtt", "com.framework.example"})，将starter-integration-mqtt包先加载，即可解决该问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aLiang-xyl/integration-mqtt"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月21日(星期五) 上午9:36
收件人:&nbsp;"aLiang-xyl/integration-mqtt"<integration-mqtt@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[aLiang-xyl/integration-mqtt] 在Spring Boot 2.1.9中无法使用 (#3)





 
在Spring Boot 2.1.9中报以下错误，但是在2.2.5中正常，能不能出一个兼容2.1.9版本的呢？
 
[2020-08-21 09:25:36.707] [MQTT Call: maintenance_analysis_server_b2c0cc548f684e308dd108754c805fbf] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter : Unhandled exception for GenericMessage [payload=test111, headers={mqtt_receivedRetained=false, id=794fcb60-066f-420c-9794-2983e7db0a87, mqtt_duplicate=false, mqtt_receivedTopic=devices/system/test, mqtt_receivedQos=1, timestamp=1597973136705}]
 org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'maintenance-analysis-server-1.testChannel'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=test111, headers={mqtt_receivedRetained=false, spanTraceId=1796e22f4f37dad7, spanId=1796e22f4f37dad7, nativeHeaders={spanTraceId=[1796e22f4f37dad7], spanId=[1796e22f4f37dad7], spanSampled=[1]}, mqtt_duplicate=false, X-B3-SpanId=1796e22f4f37dad7, X-B3-Sampled=1, X-B3-TraceId=1796e22f4f37dad7, id=1256ed97-8a4f-bd32-68cb-dd5f66488c4f, spanSampled=1, mqtt_receivedTopic=test1, mqtt_receivedQos=1, timestamp=1597973136706}]
 at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
 at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
 at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401)
 at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
 at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
 at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
 at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
 at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:205)
 at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.messageArrived(MqttPahoMessageDrivenChannelAdapter.java:350)
 at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:499)
 at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:402)
 at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:206)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
 at java.util.concurrent.FutureTask.run(FutureTask.java)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
 Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers
 at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:138)
 at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
 at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
 ... 19 common frames omitted
 [2020-08-21 09:25:36.710] [MQTT Call: maintenance_analysis_server_b2c0cc548f684e308dd108754c805fbf] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection: MqttException; retrying...

**Comment by aLiang-xyl** [comment]
现已修复了springboot2.1.9版本下订阅消息失败的问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aLiang-xyl/integration-mqtt"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月21日(星期五) 上午9:36
收件人:&nbsp;"aLiang-xyl/integration-mqtt"<integration-mqtt@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[aLiang-xyl/integration-mqtt] 在Spring Boot 2.1.9中无法使用 (#3)





 
在Spring Boot 2.1.9中报以下错误，但是在2.2.5中正常，能不能出一个兼容2.1.9版本的呢？
 
[2020-08-21 09:25:36.707] [MQTT Call: maintenance_analysis_server_b2c0cc548f684e308dd108754c805fbf] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter : Unhandled exception for GenericMessage [payload=test111, headers={mqtt_receivedRetained=false, id=794fcb60-066f-420c-9794-2983e7db0a87, mqtt_duplicate=false, mqtt_receivedTopic=devices/system/test, mqtt_receivedQos=1, timestamp=1597973136705}]
 org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'maintenance-analysis-server-1.testChannel'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=test111, headers={mqtt_receivedRetained=false, spanTraceId=1796e22f4f37dad7, spanId=1796e22f4f37dad7, nativeHeaders={spanTraceId=[1796e22f4f37dad7], spanId=[1796e22f4f37dad7], spanSampled=[1]}, mqtt_duplicate=false, X-B3-SpanId=1796e22f4f37dad7, X-B3-Sampled=1, X-B3-TraceId=1796e22f4f37dad7, id=1256ed97-8a4f-bd32-68cb-dd5f66488c4f, spanSampled=1, mqtt_receivedTopic=test1, mqtt_receivedQos=1, timestamp=1597973136706}]
 at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77)
 at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
 at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401)
 at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
 at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
 at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
 at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
 at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:205)
 at org.springframework.integration.mqtt.inbound.MqttPahoMessageDrivenChannelAdapter.messageArrived(MqttPahoMessageDrivenChannelAdapter.java:350)
 at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:499)
 at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:402)
 at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:206)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
 at java.util.concurrent.FutureTask.run(FutureTask.java)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
 Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers
 at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:138)
 at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
 at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
 ... 19 common frames omitted
 [2020-08-21 09:25:36.710] [MQTT Call: maintenance_analysis_server_b2c0cc548f684e308dd108754c805fbf] ERROR o.s.i.m.i.MqttPahoMessageDrivenChannelAdapter : Lost connection: MqttException; retrying...
